services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sudoku_backend
    volumes:
      - ./models:/app/models  # Mount models so you don't have to rebuild to update them
    networks:
      - sudoku_net

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: sudoku_frontend
    environment:
      - API_URL=http://api:8000/solve  # Tells Streamlit where the API is
    depends_on:
      - api
    networks:
      - sudoku_net

  nginx:
    image: nginx:latest
    container_name: sudoku_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - web
    networks:
      - sudoku_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - sudoku_net

networks:
  sudoku_net:
    driver: bridge
